version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/micnncim/circleci-go-playground
commands:
  restore_dep:
    steps:
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
  save_dep:
    steps:
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod/cache
  install_dep:
    steps:
      - run:
          command: go mod download
  lint:
    steps:
      - run:
          command: golint $(go list ./...)
jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_dep
      - install_dep
      - save_dep
      - lint
      - run:
          command: |
            go get golang.org/x/lint/golint

workflows:
  build:
    jobs:
      - build
